# Generated by Django 5.0.14 on 2026-07-20 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('object_name', models.CharField(help_text='Object path in the storage bucket.', max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('mime_type', models.CharField(blank=True, max_length=150)),
                ('size', models.PositiveBigIntegerField(default=0, help_text='File size in bytes.')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Website Media',
                'verbose_name_plural': 'Website Media',
                'db_table': 'WebsiteMedia',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
