# Generated by Django 6.0.6 on 2026-07-19 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
                'db_table': 'Platform',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffPlatformMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='platforms.platform')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_memberships', to='account.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Platform Membership',
                'verbose_name_plural': 'Staff Platform Memberships',
                'db_table': 'StaffPlatformMembership',
                'ordering': ['platform__name', 'user__email'],
                'constraints': [models.UniqueConstraint(fields=('user', 'platform'), name='uniq_staff_platform_membership_user_platform')],
            },
        ),
    ]
