# Generated by Django 5.0.14 on 2026-07-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='slug',
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
